'use client';
import {useMemo,useState} from 'react';
import {Calculator,SlidersHorizontal} from 'lucide-react';
type Scenario={assetValue:number;lowDamageRatio:number;highDamageRatio:number;directDamageLow:number;directDamageHigh:number;interruptionDays:number;interruptionCostPerDay:number;interruptionCost:number;totalLow:number;totalHigh:number;disclaimer:string};
const aud=(value:number)=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:0}).format(value);
export function FinancialCalcCard({scenario}:{scenario:Scenario}){
  const [damageRatio,setDamageRatio]=useState(scenario.highDamageRatio*100),[days,setDays]=useState(scenario.interruptionDays),[dailyCost,setDailyCost]=useState(scenario.interruptionCostPerDay),[adaptationBudget,setAdaptationBudget]=useState(0);
  const result=useMemo(()=>{const direct=scenario.assetValue*damageRatio/100,interruption=days*dailyCost,total=direct+interruption;return {direct,interruption,total,budgetShare:total?adaptationBudget/total*100:0}},[adaptationBudget,dailyCost,damageRatio,days,scenario.assetValue]);
  return <article className="copilot-widget calc-widget"><header><Calculator size={16}/><span>Interactive exposure stress test</span></header><div className="calc-result"><small>Adjusted gross impact scenario</small><strong>{aud(result.total)}</strong><span>{aud(result.direct)} direct + {aud(result.interruption)} interruption</span></div><div className="scenario-controls"><label><span>Damage / yield loss <b>{damageRatio.toFixed(0)}%</b></span><input type="range" min="0" max="50" step="1" value={damageRatio} onChange={event=>setDamageRatio(Number(event.target.value))}/></label><label><span>Interruption <b>{days} days</b></span><input type="range" min="0" max="90" step="1" value={days} onChange={event=>setDays(Number(event.target.value))}/></label><label><span>Daily cost <b>{aud(dailyCost)}</b></span><input type="range" min="0" max="5000" step="100" value={dailyCost} onChange={event=>setDailyCost(Number(event.target.value))}/></label><label><span>Adaptation budget <b>{aud(adaptationBudget)}</b></span><input type="range" min="0" max="100000" step="2500" value={adaptationBudget} onChange={event=>setAdaptationBudget(Number(event.target.value))}/></label></div><div className="budget-context"><SlidersHorizontal size={13}/><span>The selected budget equals <b>{result.budgetShare.toFixed(1)}%</b> of this gross impact scenario. It is an investment comparison, not a guaranteed loss reduction.</span></div><small>{scenario.disclaimer}</small></article>;
}
