import 'server-only';import {z} from 'zod';import {fetchJson,TimeoutError} from './fetch-with-policy';import {SearchResponse,type SiteLocation} from './schemas';
const VICMAP='https://services-ap1.arcgis.com/P744lA0wf4LlBZ84/arcgis/rest/services/Vicmap_Address/FeatureServer/0/query';
const Arc=z.object({exceededTransferLimit:z.boolean().optional(),features:z.array(z.object({attributes:z.object({OBJECTID:z.number(),ezi_address:z.string(),locality_name:z.string().nullable(),lga_code:z.string().nullable(),postcode:z.string().nullable(),state:z.string().nullable()}).passthrough(),geometry:z.object({x:z.number(),y:z.number()})}))});
const Nominatim=z.array(z.object({place_id:z.number(),display_name:z.string(),lat:z.string(),lon:z.string(),address:z.object({suburb:z.string().optional(),town:z.string().optional(),city:z.string().optional(),village:z.string().optional(),municipality:z.string().optional(),county:z.string().optional(),state:z.string().optional(),postcode:z.string().optional(),country_code:z.string().optional()}).passthrough()}));
const cache=new Map<string,{expires:number,value:z.infer<typeof SearchResponse>}>();
export function normalizeAddress(input:string){return input.toUpperCase().replace(/\b(UNIT|APT|APARTMENT|FLAT)\s*[A-Z0-9-]+[\s,/:-]*/g,'').replace(/\bST\b/g,'STREET').replace(/\bRD\b/g,'ROAD').replace(/\bAVE\b/g,'AVENUE').replace(/\bDR\b/g,'DRIVE').replace(/\bCT\b/g,'COURT').replace(/\bHWY\b/g,'HIGHWAY').replace(/\bVIC(?:TORIA)?\b/g,'').replace(/[%_']/g,' ').replace(/\s+/g,' ').trim().slice(0,80)}
function asVicmap(raw:z.infer<typeof Arc>,when:string):SiteLocation[]{return raw.features.map(f=>({id:f.attributes.OBJECTID,address:f.attributes.ezi_address,locality:f.attributes.locality_name??'Unknown',lga:f.attributes.lga_code??'Unknown',lat:f.geometry.y,lon:f.geometry.x,fields:{...f.attributes,provider:'Vicmap Address'},retrievedAt:when}))}
function fallbackId(placeId:number){return -(placeId+1)}
async function searchNominatim(q:string,when:string):Promise<SiteLocation[]>{const url=new URL('https://nominatim.openstreetmap.org/search');url.search=new URLSearchParams({q:`${q}, Victoria, Australia`,format:'jsonv2',addressdetails:'1',countrycodes:'au',viewbox:'140.9,-33.9,150.1,-39.3',bounded:'1',layer:'address',limit:'6'}).toString();const raw=Nominatim.parse(await fetchJson(url,false));return raw.filter(x=>x.address.country_code==='au'&&x.address.state?.toLowerCase().includes('victoria')).map(x=>({id:fallbackId(x.place_id),address:x.display_name,locality:x.address.suburb??x.address.town??x.address.city??x.address.village??'Unknown',lga:x.address.municipality??x.address.county??'Unknown',lat:Number(x.lat),lon:Number(x.lon),fields:{provider:'OpenStreetMap Nominatim',place_id:x.place_id,postcode:x.address.postcode??null},retrievedAt:when}))}
export async function searchAddress(query:string){const q=normalizeAddress(query),cached=cache.get(q);if(cached&&cached.expires>Date.now())return cached.value;if(q.length<3)return SearchResponse.parse({status:{status:'success',retrievedAt:new Date().toISOString()},matches:[],truncated:false});const url=new URL(VICMAP);url.search=new URLSearchParams({f:'json',where:`ezi_address LIKE '%${q.replaceAll(' ','%')}%'`,outFields:'OBJECTID,ezi_address,locality_name,lga_code,postcode,state',returnGeometry:'true',outSR:'4326',resultRecordCount:'8'}).toString();const when=new Date().toISOString();let vicmap:SiteLocation[]=[];let vicmapError:unknown;try{vicmap=asVicmap(Arc.parse(await fetchJson(url)),when)}catch(e){vicmapError=e}let matches=vicmap;if(!matches.length){try{matches=await searchNominatim(q,when)}catch(e){if(vicmapError)throw vicmapError;vicmapError=e}}const value=SearchResponse.parse({status:matches.length||!vicmapError?{status:'success',retrievedAt:when}:vicmapError instanceof TimeoutError?{status:'timeout',message:'Address providers timed out.'}:{status:'unavailable',message:'Address search providers are unavailable.'},matches,truncated:matches.length>=8});cache.set(q,{expires:Date.now()+300000,value});return value}
export async function addressById(id:number){if(id<0)throw new Error('Fallback address details must be supplied with the report request.');const url=new URL(VICMAP);url.search=new URLSearchParams({f:'json',objectIds:String(id),outFields:'OBJECTID,ezi_address,locality_name,lga_code,postcode,state',returnGeometry:'true',outSR:'4326',resultRecordCount:'1'}).toString();const raw=Arc.parse(await fetchJson(url)),f=raw.features[0];if(!f)throw new Error('Address no longer available');return asVicmap({...raw,features:[f]},new Date().toISOString())[0]}
