import {Report,type SiteReport,type ModelHeat} from './schemas';
import {ensemble} from './heat-indicators';
const savedAt='2026-06-30T10:00:00+10:00';
const source=(id:string,name:string,url:string)=>({id,name,url,status:{status:'success' as const,retrievedAt:savedAt}});
function history(start:number,values:number[],model:string,period:string){return {annual:values.map((v,i)=>({year:start+i,days_over_35:v,days_over_40:Math.max(0,Math.round(v*.18)),longest_run_over_35:Math.max(1,Math.round(v/5))})),retainedYears:values.length,excludedYears:0,medians:{days_over_35:values.sort((a,b)=>a-b)[Math.floor(values.length/2)],days_over_40:Math.round(values.reduce((a,b)=>a+b,0)/values.length*.18),longest_run_over_35:Math.round(values.reduce((a,b)=>a+b,0)/values.length/5)},provenance:{source:model==='ERA5-Land'?'Open-Meteo Historical Weather API':'Open-Meteo Climate API',url:model==='ERA5-Land'?'https://archive-api.open-meteo.com/v1/archive':'https://climate-api.open-meteo.com/v1/climate',retrievedAt:savedAt,period,method:model==='ERA5-Land'?'Saved illustrative annual summaries from reanalysis-shaped data; strict > thresholds.':'Saved illustrative model simulation; strict > thresholds.',unit:'days/year',model,grid:{latitude:-37.5,longitude:144.5,elevation:210,timezone:'Australia/Sydney'}}};}
function models(delta:number):ModelHeat[]{return ['CMCC_CM2_VHR4','FGOALS_f3_H','HiRAM_SIT_HR','MRI_AGCM3_2_S','EC_Earth3P_HR'].map((model,i)=>{const b=history(1981,[7+i,9+i,8+i],model,'1981-2010');const f=history(2021,[12+i+delta,14+i+delta,13+i+delta],model,'2021-2050');return {model,baseline:b,future:f,changes:{days_over_35:f.medians.days_over_35-b.medians.days_over_35,days_over_40:f.medians.days_over_40-b.medians.days_over_40,longest_run_over_35:f.medians.longest_run_over_35-b.medians.longest_run_over_35}};});}
function make(id:string,address:string,locality:string,lga:string,lat:number,lon:number,bushfire:boolean,heat:number,use:'home'|'farm',value:number,price:number):SiteReport {const ms=models(heat), historyData=history(2015,[8,10,12,9,14,15,11,16,18,17],'ERA5-Land','2015-2024'); const projections=ensemble(ms);return Report.parse({id,mode:'demo',savedAt,location:{id:id==='daylesford'?1:2,address,locality,lga,lat,lon,fields:{ezi_address:address,locality_name:locality,lga_code:lga},retrievedAt:savedAt},context:{use,assetValue:value,holdingYears:10,purchasePrice:price,concerns:['bushfire','heat']},sources:[source('address','Vicmap Address','https://services-ap1.arcgis.com/P744lA0wf4LlBZ84/arcgis/rest/services/Vicmap_Address/FeatureServer/0'),source('bushfire','Vicmap Planning Bushfire Prone Areas','https://services-ap1.arcgis.com/P744lA0wf4LlBZ84/ArcGIS/rest/services/Vicmap_Planning/FeatureServer/9'),source('history','Open-Meteo ERA5-Land reanalysis','https://archive-api.open-meteo.com/v1/archive'),source('projection','Open-Meteo CMIP6 climate models','https://climate-api.open-meteo.com/v1/climate')],bushfire,history:historyData,models:ms,projections,findings:[{id:'bushfire',category:'bushfire',title:'Mapped bushfire-prone status',finding:bushfire?'The selected location intersects the mapped Bushfire Prone Area layer.':'No intersection was returned by the mapped Bushfire Prone Area layer.',interpretation:bushfire?'A site-specific BAL assessment and planning checks should form part of due diligence.':'This single mapped designation did not intersect; it does not establish low or no bushfire risk.',sourceId:'bushfire',sourceFields:{lga_name:lga,illustrative:true},limitation:'A mapped designation is not a BAL rating, fire probability, building approval or complete risk assessment.'},{id:'heat',category:'heat',title:'Extreme heat direction',finding:`The ensemble median change is +${projections[0].medianChange} days above 35°C a year.`,interpretation:`${projections[0].agreementCount} of ${projections[0].modelCount} saved model simulations agree on an increase.`,sourceId:'projection',sourceFields:{models:projections[0].modelCount},limitation:'Modelled grid-cell changes do not predict conditions on a particular day or at a building.'},{id:'flood',category:'flood',title:'Flood evidence',finding:'Parcel-level flood evidence was not assessed because a verified, consistent source was not available for this location.',interpretation:'Obtain council or qualified flood advice before relying on this screening report.',sourceId:'none',sourceFields:{},limitation:'Not assessed must not be interpreted as low or no flood risk.'}]});}
export const demoReports=[make('daylesford','18 Vincent Street, Daylesford VIC 3460','DAYLESFORD','HEPBURN',-37.343,144.142,true,2,'home',650000,920000),make('werribee','22 Synnot Street, Werribee VIC 3030','WERRIBEE','WYNDHAM',-37.903,144.658,false,5,'farm',900000,1100000)];
export const getDemo=(id:string)=>demoReports.find(r=>r.id===id)??demoReports[0];
