import { z } from 'zod';
export const Fields = z.record(z.string(), z.union([z.string(), z.number().finite(), z.boolean(), z.null()]));
export const Status = z.discriminatedUnion('status', [z.object({status:z.literal('success'),retrievedAt:z.string()}), ...(['not_covered','unavailable','invalid_response','timeout'] as const).map(status => z.object({status:z.literal(status),message:z.string()}))]);
export type SourceStatus = z.infer<typeof Status>;
export const Location = z.object({id:z.number().int().nonnegative(),address:z.string(),locality:z.string(),lga:z.string(),lat:z.number().min(-39.3).max(-33.9),lon:z.number().min(140.9).max(150.1),fields:Fields,retrievedAt:z.string()});
export type SiteLocation = z.infer<typeof Location>;
export const Use = z.enum(['home','renovation','development','farm','warehouse/commercial','general investment']);
export const money = z.number().finite().min(0).max(1_000_000_000);
export const Context = z.object({use:Use,assetValue:money,holdingYears:z.number().int().min(1).max(100),purchasePrice:money.nullable(),concerns:z.array(z.enum(['bushfire','heat'])).min(1)});
export type DecisionContext = z.infer<typeof Context>;
export const Annual = z.object({year:z.number().int(),days_over_35:z.number(),days_over_40:z.number(),longest_run_over_35:z.number()});
export type AnnualHeat = z.infer<typeof Annual>;
export const Indicators = ['days_over_35','days_over_40','longest_run_over_35'] as const;
export const Provenance = z.object({source:z.string(),url:z.string(),retrievedAt:z.string(),period:z.string(),method:z.string(),unit:z.string(),model:z.string(),grid:z.object({latitude:z.number(),longitude:z.number(),elevation:z.number(),timezone:z.string()}).nullable()});
export const History = z.object({annual:z.array(Annual),retainedYears:z.number(),excludedYears:z.number(),medians:Annual.omit({year:true}),provenance:Provenance});
export type HeatHistory = z.infer<typeof History>;
export const ModelChange = z.object({model:z.string(),baseline:History,future:History,changes:Annual.omit({year:true})});
export type ModelHeat = z.infer<typeof ModelChange>;
export const Projection = z.object({indicator:z.enum(Indicators),baselinePeriod:z.literal('1981-2010'),futurePeriod:z.literal('2021-2050'),medianChange:z.number(),minimumChange:z.number(),maximumChange:z.number(),agreementCount:z.number(),modelCount:z.number(),modelsUsed:z.array(z.string()),unit:z.string(),direction:z.enum(['increasing','decreasing','unchanged','mixed'])});
export const Finding = z.object({id:z.string(),category:z.enum(['bushfire','heat','flood']),title:z.string(),finding:z.string(),interpretation:z.string(),sourceId:z.string(),sourceFields:Fields,limitation:z.string()});
export const Report = z.object({id:z.string(),mode:z.enum(['live','demo']),savedAt:z.string(),location:Location,context:Context,sources:z.array(z.object({id:z.string(),name:z.string(),url:z.string(),status:Status})),bushfire:z.boolean().nullable(),history:History.nullable(),models:z.array(ModelChange),projections:z.array(Projection),findings:z.array(Finding)});
export type SiteReport = z.infer<typeof Report>;
export const SearchResponse = z.object({status:Status,matches:z.array(Location),truncated:z.boolean()});
export const ReportRequest = z.object({locationId:z.number().int().nonnegative(),context:Context});
export const defaultContext: DecisionContext = {use:'home',assetValue:600000,holdingYears:10,purchasePrice:null,concerns:['bushfire','heat']};
